[ids]
*

[main]
capslock = overload(caps, esc)

[shift]
leftshift = capslock
rightshift = capslock


[caps]

h = left
j = down
k = up
l = right

space = enter
d = backspace
f = delete

p = +
o = =
i = -
u = _

/ = \
; = |
q = `
n = [
m = ]
, = {
. = }

[caps+alt]

h = home
j = pagedown
k = pageup
l = end

[caps+shift]

h = S-left
j = S-down
k = S-up
l = S-right

[caps+control]

h = C-left
j = C-down
k = C-up
l = C-right

d = C-backspace
f = C-delete

[caps+control+shift]

h = C-S-left
j = C-S-down
k = C-S-up
l = C-S-right

d = C-S-backspace
f = C-S-delete

